server:
  port: 8088
logging:
  level:
  root: ERROR
spring:
  profiles:
    active: test
  output:
    ansi:
      enabled: detect
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
    multipart:
        maxFileSize: 10Mb
        maxRequestSize: 100Mb
  messages:
    basename: i18n/messages
    cache-seconds: -1
    encoding: utf-8

  primary-datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.16.229:3306/db_31project?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    remove-abandoned: true
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 3
      maximum-pool-size: 24
      pool-name: ${spring.application.name}-CP
      idle-timeout: 10000
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      leakDetectionThreshold: 2000
#      validation-interval: 5000
#      validation-query-timeout: 5000
#      max-lifetime: 5
#      test-while-idle: true
#初始化连接
spring.primary-datasource.initial-size: 10
#最大空闲连接
spring.primary-datasource.max-idle: 20
#最小空闲连接
spring.primary-datasource.min-idle: 5
#最大连接数量
spring.primary-datasource.max-active: 50
#是否在自动回收超时连接的时候打印连接的超时错误
spring.primary-datasource.log-abandoned: true
#是否自动回收超时连接
spring.primary-datasource.remove-abandoned: true
#超时时间(以秒数为单位)
spring.primary-datasource.remove-abandoned-timeout: 180
##<!-- 超时等待时间以毫秒为单位 6000毫秒/1000等于60秒 -->
spring.primary-datasource.max-wait: 1000
spring.primary-datasource.test-while-idle: true
#检测数据库的查询语句
spring.primary-datasource.validation-query: select 1 from dual
spring.primary-datasource.test-on-borrow: true
#每隔五分钟检测空闲超过10分钟的连接
#spring.datasource.min-evictable-idle-time-millis: 600000
#spring.datasource.time-between-eviction-runs-millis: 300000
spring.primary-datasource.min-evictable-idle-time-millis: 6000
spring.primary-datasource.time-between-eviction-runs-millis: 3000

#
#logging:
#  level:
#    root: DEBUG
#    org.springframework.web: DEBUG
#    org.hibernate: DEBUG
## path: D://output/Intellij/11-Gaojiaohui/logs
#  file: logs/test.log

